version: "3.7"

services:
  news-service:
    image: ${IMAGE_NAME}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${EXPOSE_PORT}:8080"
    deploy:
      replicas: 3
      update_config:
        failure_action: rollback
        monitor: 1m
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: always
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
#      interval: 1m30s
#      timeout: 10s
#      retries: 3

