version: "3.7"

services:
  news-service:
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: ${EXPOSE_HTTP_PORT}
        protocol: tcp
        mode: ingress
#      - target: 8081
#        published: ${EXPOSE_HTTPS_PORT}
#        protocol: tcp
#        mode: ingress
    deploy:
      replicas: 3
      update_config:
        failure_action: rollback
        monitor: 1m
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
#      interval: 1m30s
#      timeout: 10s
#      retries: 3

