version: "3.7"

services:
  news-service:
    image: ${IMAGE_NAME}
    restart: always
    network_mode: "bridge"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${EXPOSE_PORT}:8080"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 1m30s
      timeout: 10s
      retries: 3

